
#Baby Buddy Scale Automations
- alias: Bottle Scale Full Button Press
  trigger:
  - platform: state
    entity_id: binary_sensor.bottle_scale_full_button
    from: 'off'
    to: 'on'
  action:
  - data_template:
      value: '{{ states("sensor.bottle_scale_value") }}'
    entity_id: input_number.bottle_scale_last_full_value
    service: input_number.set_value
- alias: Bottle Scale Empty Button Press
  trigger:
  - platform: state
    entity_id: binary_sensor.bottle_scale_empty_button
    from: 'off'
    to: 'on'
  action:
  - data_template:
      value: '{{ states("sensor.bottle_scale_value") }}'
    entity_id: input_number.bottle_scale_last_empty_value
    service: input_number.set_value

- alias: Bottle Scale Log Amount
  trigger:
  - platform: state
    entity_id: binary_sensor.bottle_scale_empty_button
    from: 'off'
    to: 'on'
  condition:
    condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(state_attr("binary_sensor.bottle_scale_empty_button","last_triggered")) | int > 180 }}'
  action:
  - delay: 00:01:00
  - service: babybuddy.add_feeding
    data:
      type: Formula
      method: Bottle
      amount: "{{ states('sensor.bottle_scale_consumed') }}"
      notes: From Bottle Scale
      start: "{{ as_timestamp(state_attr('automation.bottle_scale_full_button_press', 'last_triggered'))|timestamp_custom('%H:%M:%S',true) }}"
      end: "{{ as_timestamp(now())|timestamp_custom('%H:%M:%S',true) }}"
    target:
      device_id: baby_budy_child_device_id
